### PR TITLE
Broader support for more types of data

### PR DESCRIPTION
**Pull request by Claytonious**
* Support raw arrays
* Handle nested loosely typed dictionaries but with strong assumptions like most Json serializers do

### CODE REVIEW

**Comment by avram** [comment]
Wow that's a legit test failure!

**Comment by avram** [comment]
Why do you think that the failure is truly a Travis issue?

**Comment by Claytonious** [comment]
Yeah, that was easy!

**Comment by Claytonious** [comment]
I don't know whether it is or not yet, just want to see this turn green.

**Comment by Claytonious** [comment]
It services changes pretty darned fast.

**Pull request merged**
